version: "3"

services:
  api:
    build: ./api
    ports:
    - "3001:80"
    volumes:
    - "./data:/data"
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "mysql+mysqlconnector://root:gofastgofast@db/data"
    networks:
    - front
    - back
  
  worker:
    build: ./api
    command: celery -A dataviewerapi.celery worker --loglevel=info
    volumes:
    - "./data:/data"
    environment:
      REDIS_URL: "redis://redis:6379"
    networks:
    - back
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - "6379"
    networks:
    - back
  
  db:
    image: mariadb:10.2
    container_name: db
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gofastgofast
      MYSQL_DATABASE: data
    networks:
    - front
  
  telemetry:
    image: wuracing/telemetryapi
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
    - "9999:9999/udp"
    - "3002:80"
    networks:
    - front
    - back

networks:
  front:
  back:

# after docker-compose up, you need to run
#   docker-compose run api flask db upgrade
# to create/update the database definitions