name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      database:
        image: mariadb:10.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: set up API
      run: |
        cd api
        npm ci
        npm test
      env:
        CI: true
        DB_HOST: database
        DB_PASS: password
        DB_NAME: test

