name: Node CI

on: [push]

jobs:
  testapi:

    runs-on: ubuntu-latest

    container:
      image: node:8-jessie

    services:
      database:
        image: mariadb:10.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Install API NPM dependencies
      run: |
        cd api
        npm ci

    - name: Test API
      run: |
        npm test
      env:
        NODE_ENV: test
        DB_HOST: database
        DB_PASS: password
        DB_NAME: test

